### ISSUE TITLE
Leaderboard code organization

### ISSUE THREAD

**Issue by AndrewAlbizati** [ajockelle/CaseClaim#101]
The code for the leaderboard generation right now is quite messy. To improve, we should add a class to store all of the data inside of. For example, the class's constructor will sift through the data and create fields for specific situations like monthly_pings_dict, monthly_pings_list, semester_kudos_list, etc.

Hopefully with this the bot will only need to iterate through every case only once.

**Comment by ajockelle** [comment]
Modify the leaderboard embed to be a collection of 4 inline fields broken up into a 2x2 inline field array.

Additionally make the server icon based off the monthly leading team instead of the semester leading team.
