### ISSUE TITLE
Historic leaderboard

### ISSUE THREAD

**Issue by AndrewAlbizati** [ajockelle/CaseClaim#118]
A new feature to request a leaderboard with historic data. This leaderboard would be presented in the same style as the current leaderboard, although without the Refresh or My Rank buttons.

Example command (subject to change) **/hleaderboard [Month/Year options] [Semester options]**

The [month/year] options would be September 2023, October 2023, November 2023...
The [semester] options would be Summer 2023, Fall 2023, Spring 2024...

**Comment by ajockelle** [comment]
Could this be structured as an optional parameter to pass into the leaderboard command?

**Comment by AndrewAlbizati** [comment]
Here's my idea:

**/leaderboard [start (MM/YY)] [end (MM/YY)]** where the two parameters are optional. There are three options:

1. If neither parameter is used, the normal leaderboard will be displayed.
2. If the start parameter is used, an ephemeral leaderboard will be sent with the data until present
3. If both parameters are used, an ephemeral leaderboard will be sent with the data until the end date.

**Comment by ajockelle** [comment]
Nice move making it ephemeral, that'd work out great. We'll need to update the /help as well with instructions.

**Comment by AndrewAlbizati** [comment]
Do you think we should open this command up to techs (only ephemeral versions)?

**Comment by ajockelle** [comment]
I don't see any issues with that.
