### ISSUE TITLE
Leaderboard icon changing for leaderboard

### ISSUE THREAD

**Issue by AndrewAlbizati** [ajockelle/CaseClaim#27]
![Screenshot 2023-08-03 at 10 29 19 PM](https://github.com/ajockelle/CaseClaim/assets/76797236/972e2adb-cfd4-42d6-a351-75a43fbfad60)

The icon will change depending on which team is in first place. For this, each team will need to be assigned an icon. Teams should be added to their own table in the MySQL database in order to keep track of this data.

**Comment by ajockelle** [comment]
I was thinking that we remove this icon in its entirety to reduce the width of the embed.

**Comment by AndrewAlbizati** [comment]
> 

Done!

**Comment by ajockelle** [comment]
- Move server icon to the leaderboard embed author field. 
- Move the Team Ranks to the first field. 
- Change Author field to "Leaderboard"
- Remove "Ranks" from each of the field titles
- Remove parentheses and change to | deliniaters
