### ISSUE TITLE
15 Minute Warning

### ISSUE THREAD

**Issue by AndrewAlbizati** [ajockelle/CaseClaim#40]
Warn a tech when a case has been claimed with the same number within the last 15 minutes. Prompt them with an ephemeral message that says "Case 00000000 has been claimed by **user** in the last 15 minutes. Would you like to claim it?" and send with a Yes and No button. If No is pressed, the message is deleted. If Yes is pressed, claim the case as normal.

**Comment by ajockelle** [comment]
In the case completed prompt, edit to say,
"Case has been marked as complete, to view all your cases use /mycases"
