### ISSUE TITLE
Award Points /award

### ISSUE THREAD

**Issue by ajockelle** [ajockelle/CaseClaim#49]
Command restricted to leads / PAs

/award <@team> <num_points> <reason>

Behavior:
- Adds 3 points to the mentioned team. 
- Sends a message in #general 
<@Role has been awarded <num_points> by <@lead/PA> for <reason>

**Comment by AndrewAlbizati** [comment]
I'm not sure that this feature will be well-received. I feel like the leaderboard should be based only on claims.

**Comment by AndrewAlbizati** [comment]
Create a new table Teams which would have each row's primary key be the role ID and include the amount of points the team has won (bigint). Look into the option of storing the icon in the table instead of `config.json`.
