### ISSUE TITLE
/myrank

### ISSUE THREAD

**Issue by ajockelle** [ajockelle/CaseClaim#74]
When calculating percentages for myrank, use the formula;

(checked) / (checked) + (pinged) 

effectively excluding 'done'

**Comment by AndrewAlbizati** [comment]
Done cases are already excluded in the `My Rank` button.

From `leaderboard_view.py`, line 179.

```py
for claim in claims:
    # Filter out DONE cases
    if claim.status == Status.DONE:
        continue
```
