### ISSUE TITLE
G-Chat Case Claim

### ISSUE THREAD

**Issue by ajockelle** [ajockelle/CaseClaim#95]
Investigate the viability of a light-weight bot that checks the last `<num>` messages or messages sent within the last `<num>` minutes in a Google Chat channel to see if a case was previously sent. The bot would send a message in the chat warning the technician that the case was recently claimed by another user. 

This would be used in a Google Chat where users simply send the case messages as the 8 digit number.

This would be a stand-alone application and would need a simple UI to control the number of messages sent or the number of minutes since last sent.

**Comment by AndrewAlbizati** [comment]
Access to the Google API is disabled for USD accounts, I'm not sure how else this could be implemented.
