### ISSUE TITLE
Error with Announcments

### ISSUE THREAD

**Issue by ajockelle** [ajockelle/CaseClaim#97]
The outage announcement ran into an error. 

This error occurred after sending an announcement announcement. 

The outage announcement sent a message in the `#announcement channel`, but did not delete the `@here` message that it sent.

[AnnouncementError.txt](https://github.com/ajockelle/CaseClaim/files/12704245/AnnouncementError.txt)

**Comment by AndrewAlbizati** [comment]
Looks like this error stems from this:
```
Traceback (most recent call last):
  File "C:\Users\Helpdesk\AppData\Local\Programs\Python\Python311\Lib\site-packages\mysql\connector\connection_cext.py", line 633, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Data too long for column 'parent_case' at row 1

The above exception was the direct cause of the following exception:
```

I can work on a patch. The parent case can only be a varchar(8), so to fix this I'll add an if statement to check the length of the parent case ID.
