### ISSUE TITLE
Ping timing

### ISSUE THREAD

**Issue by ajockelle** [ajockelle/CaseClaim#99]
When outside of work hours, 7AM to 6PM M-F to make it simple, do not send ping notifications, send them the next day at 7AM.

**Comment by AndrewAlbizati** [comment]
I can make the bot not send ping notifications outside work hours, it would be an easy fix.

For making them send the next day, that'll be a bit more complicated. Maybe it would work best to delay that part of development to a later time.

**Comment by AndrewAlbizati** [comment]
If the case is outside of work hours, then add to pending pinged table in the database.

At 7am every weekday morning that is not a holiday, create pinged threads from that database. This can be timed using a looping event.
